repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
