site_name: solnlib

theme:
  name: "material"
  custom_dir: docs/theme_overrides
  palette:
    primary: "black"
    accent: "orange"
  features:
    - content.code.copy
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: True
  - smarty
  - fenced_code
  - sane_lists
  - codehilite

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: true
  - autorefs
  - search
  - print-site  # should be at the end

nav:
  - Home: index.md
  - Release 6.0.0: release_6_0_0.md
  - Contributing: contributing.md
  - References:
      - modular_input:
          - "checkpointer.py": modular_input/checkpointer.md
          - "event.py": modular_input/event.md
          - "event_writer.py": modular_input/event_writer.md
          - "modular_input.py": modular_input/modular_input.md
      - "acl.py": acl.md
      - "alerts_rest_client.py": alerts_rest_client.md
      - "bulletin_rest_client.py": bulletin_rest_client.md
      - "credentials.py": credentials.md
      - "conf_manager.py": conf_manager.md
      - "file_monitor.py": file_monitor.md
      - "hec_config.py": hec_config.md
      - "log.py": log.md
      - "net_utils.py": net_utils.md
      - "orphan_process_monitor.py": orphan_process_monitor.md
      - "pattern.py": pattern.md
      - "server_info.py": server_info.md
      - "splunk_rest_client.py": splunk_rest_client.md
      - "bulletin_rest_client.py": bulletin_rest_client.md
      - "splunkenv.py": splunkenv.md
      - "time_parser.py": time_parser.md
      - "timer_queue.py": timer_queue.md
      - "user_access.py": user_access.md
      - "utils.py": utils.md
