site_name: Splunk Solutions SDK

theme:
  name: "material"
  palette:
    primary: "black"
    accent: "orange"

markdown_extensions:
  - toc:
      permalink: True
  - smarty
  - fenced_code
  - sane_lists
  - codehilite

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_if_no_docstring: true

nav:
  - Home: index.md
  - References:
      - "credentials.py": credentials.md
      - "conf_manager.py": conf_manager.md
      - "log.py": log.md
      - "server_info.py": server_info.md
      - "splunk_rest_client.py": splunk_rest_client.md
