
# jscpd:ignore-start
name: build-test-release
on:
  push:
    branches:
      - "main"
      - "develop"
      - "github-actions-migration"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [main, develop]

jobs:
  # copy of TA semgrep implementation
  semgrep:
    runs-on: ubuntu-latest
    name: security-sast-semgrep
    steps:
      - uses: actions/checkout@v2
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
          publishToken: ${{ secrets.SEMGREP_PUBLISH_TOKEN }}

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tools
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Build
        run: |
          source $HOME/.poetry/env
          poetry install
          poetry run poetry-dynamic-versioning
          poetry build
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: dist
          path: dist
      # TODO check if needed
      # GA error: No files were found with the provided path: output. No artifacts will be uploaded.
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: output
          path: output

  run-unit-tests:
    name: test-unit
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: run tests
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env
          poetry install
          poetry run pytest --junitxml=test-results/results.xml --cov=solnlib --cov-report=html tests
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: unit tests test-results
          path: test-results
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: unit tests htmlcov report
          path: htmlcov
