name: docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          # shellcheck disable=SC1090
          source "$HOME/.poetry/env"
          poetry install
          poetry add --dev mkdocs mkdocs-material mkdocstrings
          poetry run mkdocs gh-deploy --force
