name: Release-Notes-Preview

on:
  pull_request:
  issue_comment:
    types: [edited]

jobs:
  call-workflow-preview:
    uses: arys-splunk/github-workflows-reuse/.github/workflows/release-notes.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
